Import of GWARD/btparse-0.34 from CPAN.
gitpan-cpan-distribution: btparse
gitpan-cpan-version:      0.34
gitpan-cpan-path:         GWARD/btparse-0.34.tar.gz
gitpan-cpan-author:       GWARD
gitpan-cpan-maturity:     released

diff --git a/tests/Makefile.in b/tests/Makefile.in
--- a/tests/Makefile.in
+++ b/tests/Makefile.in
@@ -83,8 +83,7 @@ EGREP = @EGREP@
 F77 = @F77@
 GCJ = @GCJ@
 GCJFLAGS = @GCJFLAGS@
-
-INCLUDES = @INCLUDES@ -I@abs_top_srcdir@/src @PCCTS_INCLUDES@
+INCLUDES = @INCLUDES@ -I@abs_top_srcdir@/src
 INSTALL_STRIP_PROGRAM = @INSTALL_STRIP_PROGRAM@
 LIBTOOL = @LIBTOOL@
 LN_S = @LN_S@
@@ -101,43 +100,78 @@ VERSION = @VERSION@
 am__include = @am__include@
 am__quote = @am__quote@
 install_sh = @install_sh@
+
+AM_CFLAGS = -DDATA_DIR=\"$(srcdir)/data\"
 LDADD = ../src/libbtparse.la
 
-bin_PROGRAMS = bibparse
-noinst_PROGRAMS = biblex dumpnames
+# The first three are real test programs, ie. they run non-interactively
+# and it's fairly obvious whether the tests passed or not.  The others
+# (macro_test etc.) are interactive and require a good understanding
+# of BibTeX and btparse to understand what's going on -- which is why
+# they're not listed in TESTS below.
+check_PROGRAMS = simple_test \
+                 read_test \
+                 postprocess_test \
+                 macro_test \
+                 case_test \
+                 name_test \
+                 purify_test
 
-bibparse_SOURCES = bibparse.c args.c getopt.c getopt1.c
 
-biblex_SOURCES = biblex.c
+simple_test_SOURCES = simple_test.c testlib.c
+read_test_SOURCES = read_test.c testlib.c
+postprocess_test_SOURCES = postprocess_test.c
+macro_test_SOURCES = macro_test.c
+case_test_SOURCES = case_test.c
+name_test_SOURCES = name_test.c
+purify_test_SOURCES = purify_test.c
 
-dumpnames_SOURCES = dumpnames.c
+TESTS = read_test simple_test postprocess_test
 
-noinst_HEADERS = args.h getopt.h
-subdir = progs
+EXTRA_DIST = testlib.h $(wildcard data/*.bib) data/TESTS
+subdir = tests
 mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
 CONFIG_HEADER = $(top_builddir)/src/bt_config.h \
 	$(top_builddir)/src/btparse.h
 CONFIG_CLEAN_FILES =
-bin_PROGRAMS = bibparse$(EXEEXT)
-noinst_PROGRAMS = biblex$(EXEEXT) dumpnames$(EXEEXT)
-PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)
-
-am_biblex_OBJECTS = biblex.$(OBJEXT)
-biblex_OBJECTS = $(am_biblex_OBJECTS)
-biblex_LDADD = $(LDADD)
-biblex_DEPENDENCIES = ../src/libbtparse.la
-biblex_LDFLAGS =
-am_bibparse_OBJECTS = bibparse.$(OBJEXT) args.$(OBJEXT) getopt.$(OBJEXT) \
-	getopt1.$(OBJEXT)
-bibparse_OBJECTS = $(am_bibparse_OBJECTS)
-bibparse_LDADD = $(LDADD)
-bibparse_DEPENDENCIES = ../src/libbtparse.la
-bibparse_LDFLAGS =
-am_dumpnames_OBJECTS = dumpnames.$(OBJEXT)
-dumpnames_OBJECTS = $(am_dumpnames_OBJECTS)
-dumpnames_LDADD = $(LDADD)
-dumpnames_DEPENDENCIES = ../src/libbtparse.la
-dumpnames_LDFLAGS =
+check_PROGRAMS = simple_test$(EXEEXT) read_test$(EXEEXT) \
+	postprocess_test$(EXEEXT) macro_test$(EXEEXT) \
+	case_test$(EXEEXT) name_test$(EXEEXT) purify_test$(EXEEXT)
+am_case_test_OBJECTS = case_test.$(OBJEXT)
+case_test_OBJECTS = $(am_case_test_OBJECTS)
+case_test_LDADD = $(LDADD)
+case_test_DEPENDENCIES = ../src/libbtparse.la
+case_test_LDFLAGS =
+am_macro_test_OBJECTS = macro_test.$(OBJEXT)
+macro_test_OBJECTS = $(am_macro_test_OBJECTS)
+macro_test_LDADD = $(LDADD)
+macro_test_DEPENDENCIES = ../src/libbtparse.la
+macro_test_LDFLAGS =
+am_name_test_OBJECTS = name_test.$(OBJEXT)
+name_test_OBJECTS = $(am_name_test_OBJECTS)
+name_test_LDADD = $(LDADD)
+name_test_DEPENDENCIES = ../src/libbtparse.la
+name_test_LDFLAGS =
+am_postprocess_test_OBJECTS = postprocess_test.$(OBJEXT)
+postprocess_test_OBJECTS = $(am_postprocess_test_OBJECTS)
+postprocess_test_LDADD = $(LDADD)
+postprocess_test_DEPENDENCIES = ../src/libbtparse.la
+postprocess_test_LDFLAGS =
+am_purify_test_OBJECTS = purify_test.$(OBJEXT)
+purify_test_OBJECTS = $(am_purify_test_OBJECTS)
+purify_test_LDADD = $(LDADD)
+purify_test_DEPENDENCIES = ../src/libbtparse.la
+purify_test_LDFLAGS =
+am_read_test_OBJECTS = read_test.$(OBJEXT) testlib.$(OBJEXT)
+read_test_OBJECTS = $(am_read_test_OBJECTS)
+read_test_LDADD = $(LDADD)
+read_test_DEPENDENCIES = ../src/libbtparse.la
+read_test_LDFLAGS =
+am_simple_test_OBJECTS = simple_test.$(OBJEXT) testlib.$(OBJEXT)
+simple_test_OBJECTS = $(am_simple_test_OBJECTS)
+simple_test_LDADD = $(LDADD)
+simple_test_DEPENDENCIES = ../src/libbtparse.la
+simple_test_LDFLAGS =
 
 DEFS = @DEFS@
 DEFAULT_INCLUDES =  -I. -I$(srcdir) -I$(top_builddir)/src -I$(top_builddir)/src
@@ -146,9 +180,11 @@ LDFLAGS = @LDFLAGS@
 LIBS = @LIBS@
 depcomp = $(SHELL) $(top_srcdir)/depcomp
 am__depfiles_maybe = depfiles
-@AMDEP_TRUE@DEP_FILES = ./$(DEPDIR)/args.Po ./$(DEPDIR)/biblex.Po \
-@AMDEP_TRUE@	./$(DEPDIR)/bibparse.Po ./$(DEPDIR)/dumpnames.Po \
-@AMDEP_TRUE@	./$(DEPDIR)/getopt.Po ./$(DEPDIR)/getopt1.Po
+@AMDEP_TRUE@DEP_FILES = ./$(DEPDIR)/case_test.Po \
+@AMDEP_TRUE@	./$(DEPDIR)/macro_test.Po ./$(DEPDIR)/name_test.Po \
+@AMDEP_TRUE@	./$(DEPDIR)/postprocess_test.Po \
+@AMDEP_TRUE@	./$(DEPDIR)/purify_test.Po ./$(DEPDIR)/read_test.Po \
+@AMDEP_TRUE@	./$(DEPDIR)/simple_test.Po ./$(DEPDIR)/testlib.Po
 COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
 	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
 LTCOMPILE = $(LIBTOOL) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) \
@@ -157,12 +193,12 @@ CCLD = $(CC)
 LINK = $(LIBTOOL) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
 	$(AM_LDFLAGS) $(LDFLAGS) -o $@
 CFLAGS = @CFLAGS@
-DIST_SOURCES = $(biblex_SOURCES) $(bibparse_SOURCES) \
-	$(dumpnames_SOURCES)
-HEADERS = $(noinst_HEADERS)
-
-DIST_COMMON = $(noinst_HEADERS) Makefile.am Makefile.in
-SOURCES = $(biblex_SOURCES) $(bibparse_SOURCES) $(dumpnames_SOURCES)
+DIST_SOURCES = $(case_test_SOURCES) $(macro_test_SOURCES) \
+	$(name_test_SOURCES) $(postprocess_test_SOURCES) \
+	$(purify_test_SOURCES) $(read_test_SOURCES) \
+	$(simple_test_SOURCES)
+DIST_COMMON = Makefile.am Makefile.in
+SOURCES = $(case_test_SOURCES) $(macro_test_SOURCES) $(name_test_SOURCES) $(postprocess_test_SOURCES) $(purify_test_SOURCES) $(read_test_SOURCES) $(simple_test_SOURCES)
 
 all: all-am
 
@@ -170,54 +206,37 @@ all: all-am
 .SUFFIXES: .c .lo .o .obj
 $(srcdir)/Makefile.in:  Makefile.am  $(top_srcdir)/configure.ac $(ACLOCAL_M4)
 	cd $(top_srcdir) && \
-	  $(AUTOMAKE) --gnu  progs/Makefile
+	  $(AUTOMAKE) --gnu  tests/Makefile
 Makefile:  $(srcdir)/Makefile.in  $(top_builddir)/config.status
 	cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)
-binPROGRAMS_INSTALL = $(INSTALL_PROGRAM)
-install-binPROGRAMS: $(bin_PROGRAMS)
-	@$(NORMAL_INSTALL)
-	$(mkinstalldirs) $(DESTDIR)$(bindir)
-	@list='$(bin_PROGRAMS)'; for p in $$list; do \
-	  p1=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
-	  if test -f $$p \
-	     || test -f $$p1 \
-	  ; then \
-	    f=`echo "$$p1" | sed 's,^.*/,,;$(transform);s/$$/$(EXEEXT)/'`; \
-	   echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f"; \
-	   $(INSTALL_PROGRAM_ENV) $(LIBTOOL) --mode=install $(binPROGRAMS_INSTALL) $$p $(DESTDIR)$(bindir)/$$f; \
-	  else :; fi; \
-	done
 
-uninstall-binPROGRAMS:
-	@$(NORMAL_UNINSTALL)
-	@list='$(bin_PROGRAMS)'; for p in $$list; do \
-	  f=`echo "$$p" | sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
-	  echo " rm -f $(DESTDIR)$(bindir)/$$f"; \
-	  rm -f $(DESTDIR)$(bindir)/$$f; \
-	done
-
-clean-binPROGRAMS:
-	@list='$(bin_PROGRAMS)'; for p in $$list; do \
+clean-checkPROGRAMS:
+	@list='$(check_PROGRAMS)'; for p in $$list; do \
 	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
 	  echo " rm -f $$p $$f"; \
 	  rm -f $$p $$f ; \
 	done
-
-clean-noinstPROGRAMS:
-	@list='$(noinst_PROGRAMS)'; for p in $$list; do \
-	  f=`echo $$p|sed 's/$(EXEEXT)$$//'`; \
-	  echo " rm -f $$p $$f"; \
-	  rm -f $$p $$f ; \
-	done
-biblex$(EXEEXT): $(biblex_OBJECTS) $(biblex_DEPENDENCIES) 
-	@rm -f biblex$(EXEEXT)
-	$(LINK) $(biblex_LDFLAGS) $(biblex_OBJECTS) $(biblex_LDADD) $(LIBS)
-bibparse$(EXEEXT): $(bibparse_OBJECTS) $(bibparse_DEPENDENCIES) 
-	@rm -f bibparse$(EXEEXT)
-	$(LINK) $(bibparse_LDFLAGS) $(bibparse_OBJECTS) $(bibparse_LDADD) $(LIBS)
-dumpnames$(EXEEXT): $(dumpnames_OBJECTS) $(dumpnames_DEPENDENCIES) 
-	@rm -f dumpnames$(EXEEXT)
-	$(LINK) $(dumpnames_LDFLAGS) $(dumpnames_OBJECTS) $(dumpnames_LDADD) $(LIBS)
+case_test$(EXEEXT): $(case_test_OBJECTS) $(case_test_DEPENDENCIES) 
+	@rm -f case_test$(EXEEXT)
+	$(LINK) $(case_test_LDFLAGS) $(case_test_OBJECTS) $(case_test_LDADD) $(LIBS)
+macro_test$(EXEEXT): $(macro_test_OBJECTS) $(macro_test_DEPENDENCIES) 
+	@rm -f macro_test$(EXEEXT)
+	$(LINK) $(macro_test_LDFLAGS) $(macro_test_OBJECTS) $(macro_test_LDADD) $(LIBS)
+name_test$(EXEEXT): $(name_test_OBJECTS) $(name_test_DEPENDENCIES) 
+	@rm -f name_test$(EXEEXT)
+	$(LINK) $(name_test_LDFLAGS) $(name_test_OBJECTS) $(name_test_LDADD) $(LIBS)
+postprocess_test$(EXEEXT): $(postprocess_test_OBJECTS) $(postprocess_test_DEPENDENCIES) 
+	@rm -f postprocess_test$(EXEEXT)
+	$(LINK) $(postprocess_test_LDFLAGS) $(postprocess_test_OBJECTS) $(postprocess_test_LDADD) $(LIBS)
+purify_test$(EXEEXT): $(purify_test_OBJECTS) $(purify_test_DEPENDENCIES) 
+	@rm -f purify_test$(EXEEXT)
+	$(LINK) $(purify_test_LDFLAGS) $(purify_test_OBJECTS) $(purify_test_LDADD) $(LIBS)
+read_test$(EXEEXT): $(read_test_OBJECTS) $(read_test_DEPENDENCIES) 
+	@rm -f read_test$(EXEEXT)
+	$(LINK) $(read_test_LDFLAGS) $(read_test_OBJECTS) $(read_test_LDADD) $(LIBS)
+simple_test$(EXEEXT): $(simple_test_OBJECTS) $(simple_test_DEPENDENCIES) 
+	@rm -f simple_test$(EXEEXT)
+	$(LINK) $(simple_test_LDFLAGS) $(simple_test_OBJECTS) $(simple_test_LDADD) $(LIBS)
 
 mostlyclean-compile:
 	-rm -f *.$(OBJEXT) core *.core
@@ -225,12 +244,14 @@ mostlyclean-compile:
 distclean-compile:
 	-rm -f *.tab.c
 
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/args.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/biblex.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/bibparse.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/dumpnames.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/getopt.Po@am__quote@
-@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/getopt1.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/case_test.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/macro_test.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/name_test.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/postprocess_test.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/purify_test.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/read_test.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/simple_test.Po@am__quote@
+@AMDEP_TRUE@@am__include@ @am__quote@./$(DEPDIR)/testlib.Po@am__quote@
 
 distclean-depend:
 	-rm -rf ./$(DEPDIR)
@@ -299,12 +320,68 @@ GTAGS:
 
 distclean-tags:
 	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH
+
+check-TESTS: $(TESTS)
+	@failed=0; all=0; xfail=0; xpass=0; \
+	srcdir=$(srcdir); export srcdir; \
+	list='$(TESTS)'; \
+	if test -n "$$list"; then \
+	  for tst in $$list; do \
+	    if test -f ./$$tst; then dir=./; \
+	    elif test -f $$tst; then dir=; \
+	    else dir="$(srcdir)/"; fi; \
+	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+	        xpass=`expr $$xpass + 1`; \
+	        failed=`expr $$failed + 1`; \
+	        echo "XPASS: $$tst"; \
+	      ;; \
+	      *) \
+	        echo "PASS: $$tst"; \
+	      ;; \
+	      esac; \
+	    elif test $$? -ne 77; then \
+	      all=`expr $$all + 1`; \
+	      case " $(XFAIL_TESTS) " in \
+	      *" $$tst "*) \
+	        xfail=`expr $$xfail + 1`; \
+	        echo "XFAIL: $$tst"; \
+	      ;; \
+	      *) \
+	        failed=`expr $$failed + 1`; \
+	        echo "FAIL: $$tst"; \
+	      ;; \
+	      esac; \
+	    fi; \
+	  done; \
+	  if test "$$failed" -eq 0; then \
+	    if test "$$xfail" -eq 0; then \
+	      banner="All $$all tests passed"; \
+	    else \
+	      banner="All $$all tests behaved as expected ($$xfail expected failures)"; \
+	    fi; \
+	  else \
+	    if test "$$xpass" -eq 0; then \
+	      banner="$$failed of $$all tests failed"; \
+	    else \
+	      banner="$$failed of $$all tests did not behave as expected ($$xpass unexpected passes)"; \
+	    fi; \
+	  fi; \
+	  dashes=`echo "$$banner" | sed s/./=/g`; \
+	  echo "$$dashes"; \
+	  echo "$$banner"; \
+	  echo "$$dashes"; \
+	  test "$$failed" -eq 0; \
+	else :; fi
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
 
 top_distdir = ..
 distdir = $(top_distdir)/$(PACKAGE)-$(VERSION)
 
 distdir: $(DISTFILES)
+	$(mkinstalldirs) $(distdir)/data
 	@list='$(DISTFILES)'; for file in $$list; do \
 	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
 	  dir=`echo "$$file" | sed -e 's,/[^/]*$$,,'`; \
@@ -326,11 +403,12 @@ distdir: $(DISTFILES)
 	  fi; \
 	done
 check-am: all-am
+	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
+	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
 check: check-am
-all-am: Makefile $(PROGRAMS) $(HEADERS)
+all-am: Makefile
 
 installdirs:
-	$(mkinstalldirs) $(DESTDIR)$(bindir)
 
 install: install-am
 install-exec: install-exec-am
@@ -358,8 +436,7 @@ maintainer-clean-generic:
 	@echo "it deletes files that may require special tools to rebuild."
 clean: clean-am
 
-clean-am: clean-binPROGRAMS clean-generic clean-libtool \
-	clean-noinstPROGRAMS mostlyclean-am
+clean-am: clean-checkPROGRAMS clean-generic clean-libtool mostlyclean-am
 
 distclean: distclean-am
 
@@ -376,7 +453,7 @@ info-am:
 
 install-data-am:
 
-install-exec-am: install-binPROGRAMS
+install-exec-am:
 
 install-info: install-info-am
 
@@ -393,19 +470,19 @@ mostlyclean: mostlyclean-am
 mostlyclean-am: mostlyclean-compile mostlyclean-generic \
 	mostlyclean-libtool
 
-uninstall-am: uninstall-binPROGRAMS uninstall-info-am
+uninstall-am: uninstall-info-am
 
-.PHONY: GTAGS all all-am check check-am clean clean-binPROGRAMS \
-	clean-generic clean-libtool clean-noinstPROGRAMS distclean \
+.PHONY: GTAGS all all-am check check-TESTS check-am clean \
+	clean-checkPROGRAMS clean-generic clean-libtool distclean \
 	distclean-compile distclean-depend distclean-generic \
 	distclean-libtool distclean-tags distdir dvi dvi-am info \
-	info-am install install-am install-binPROGRAMS install-data \
-	install-data-am install-exec install-exec-am install-info \
-	install-info-am install-man install-strip installcheck \
-	installcheck-am installdirs maintainer-clean \
-	maintainer-clean-generic mostlyclean mostlyclean-compile \
-	mostlyclean-generic mostlyclean-libtool tags uninstall \
-	uninstall-am uninstall-binPROGRAMS uninstall-info-am
+	info-am install install-am install-data install-data-am \
+	install-exec install-exec-am install-info install-info-am \
+	install-man install-strip installcheck installcheck-am \
+	installdirs maintainer-clean maintainer-clean-generic \
+	mostlyclean mostlyclean-compile mostlyclean-generic \
+	mostlyclean-libtool tags uninstall uninstall-am \
+	uninstall-info-am
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
